name: Build and Draft Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (ej: v1.2.3)'
        required: true

permissions:
  contents: write

jobs:
  run_tests:
    uses: ./.github/workflows/testing.yml

  build_and_release:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Descarga el código fuente del repositorio
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # Selecciona la versión de Node.js

      - name: Install dependencies
        run: npm ci # Instala dependencias desde package-lock.json

      - name: Build Project
        run: npm run build # Compila el proyecto

      - name: Compress build folder
        run: zip -r build-output.zip dist # Comprime la carpeta de salida

      - name: Create Draft Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          draft: true
          files: build-output.zip
        env:

          # Este valor utiliza el token de autenticación proporcionado automáticamente por GitHub Actions a través del workspace.
          # No es necesario definir un token manualmente, ya que `${{ secrets.GITHUB_TOKEN }}` es gestionado de forma segura por GitHub
          # para permitir que los flujos de trabajo interactúen con la API de GitHub.
          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}