# .github/workflows/release-build.yml
name: Build on Release

on:
  release:
    types: [published]

jobs:
  run_tests:
    uses: ./.github/workflows/testing.yml

  build:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Descarga el código fuente del repositorio
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Selecciona la versión de Node.js

      - name: Install dependencies
        run: npm ci # Instala dependencias desde package-lock.json

      - name: Build Project
        run: npm run build # Compila el proyecto

      - name: Compress build folder
        run: zip -r build-output.zip dist # Comprime la carpeta de salida

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build-output.zip # Sube el archivo comprimido como asset del release
        env:

          # Este valor utiliza el token de autenticación proporcionado automáticamente por GitHub Actions a través del workspace.
          # No es necesario definir un token manualmente, ya que `${{ secrets.GITHUB_TOKEN }}` es gestionado de forma segura por GitHub
          # para permitir que los flujos de trabajo interactúen con la API de GitHub.
          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}