name: Run Jest Tests

on:
  push:
    branches: [ main, develop ]
    branches-ignore: [ 'feature/**' ]  # Ignora pushes a feature/*
    
  pull_request:
    branches: [ main, develop ]  # PRs hacia main/develop (no necesitas branches-ignore)

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18.x', '20.x', '21.x' ]  # Matriz de versiones
    name: Node ${{ matrix.node-version }} Tests
    steps:
      - uses: actions/checkout@v4  # Descarga el código del repositorio
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}  # Usa la versión de la matriz

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test